version: "3"

networks:
  thorcast:

services:
  db:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=thorcast
      - POSTGRES_PASSWORD=thorcast
      - POSTGRES_DB=thorcast
    networks:
      - thorcast
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker_volumes/thor_db:/var/lib/postgresql/data
      - ../../thorcast-server/db/models/ddl.sql:/docker-entrypoint-initdb.d/initdb.sql
    command: [postgres, -c, max_connections=10000]
  redis:
    image: redis:6.0.5
    networks:
      - thorcast
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    entrypoint: redis-server /usr/local/etc/redis.conf
  thorcast-server:
    build: ../../thorcast-server
    volumes:
      - ../../thorcast-server:/app/thorcast-server
    networks:
      - thorcast
    ports:
      - "8000:8000"
    env_file:
      - ../../thorcast-server/.env
  thorcast-discord:
    build: ../../thorcast-discord
    volumes:
      - ../../thorcast-discord:/app/thorcast-discord
    networks:
      - thorcast
    env_file:
      - ../../thorcast-discord/.env
  thorcast-slack:
    build: ../../thorcast-slack
    volumes:
      - ../../thorcast-slack:/app/thorcast-slack
    networks:
      - thorcast
    env_file:
      - ../../thorcast-slack/.env
